In [25]:
import torch
import random
import math
from torch.utils.data import Dataset

import pandas as pd
import numpy as np
import networkx as nx
import sys


In [60]:
def initialize_graph():
    
        coordinates = pd.read_csv("../vienna_data/vienna_dist.csv", header = None, sep=' ')
        coordinates.columns = ['coord1','coord2','dist']
        graph = nx.DiGraph()

        # add the rows to the graph for shortest path and distance calculations
        for _, row in coordinates.iterrows():
            graph.add_edge(row['coord1'], row['coord2'], weight=row['dist'])

        return graph


def precompute_shortest_path(graph, start_node, end_node):

    shortest_path = nx.shortest_path(graph, start_node, end_node)

    # TODO: distance need to be normalized afterwords
    shortest_path_length = sum(graph.get_edge_data(u, v)['weight'] 
                               for u, v in zip(shortest_path, shortest_path[1:]))

    return shortest_path_length 


def get_distanceLL(lat1, lon1, lat2, lon2):

    R = 6371  # Radius of the Earth in kilometers

    lat1_rad = math.radians(lat1)
    lon1_rad = math.radians(lon1)
    lat2_rad = math.radians(lat2)
    lon2_rad = math.radians(lon2)

    dlat = lat2_rad - lat1_rad
    dlon = lon2_rad - lon1_rad

    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2) ** 2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    distance = R * c
    return distance


def get_NearestNodeLL(lat, lon, lats, lons):
    nearest = (-1, sys.float_info.max)
    for i in range(len(lats)):
        dist = get_distanceLL(lat, lon, lats[i], lons[i])
        if dist < nearest[1]:
            nearest = (i, dist)
    return nearest[0]



def get_depot_location(data_vienna):

    ll = (48.178808, 16.438460)
    lat = ll[0] / 180 * math.pi
    lon = ll[1] / 180 * math.pi
    lats = data_vienna['lats']
    lons = data_vienna['lons']
    depot = get_NearestNodeLL(lat, lon, lats, lons)
    depot_coordinates = np.array(data_vienna[data_vienna['id']==depot][['id','xcoords', 'ycoords']])

    return depot_coordinates

def get_customers_coordinates(data_vienna, batch_size, customers_count, depot):

    torch.manual_seed(42)

    # Excluding depot id from the customers selection
    data_vienna_without_depot = data_vienna[data_vienna['id'] != int(depot[0][0])].reset_index()

    # Sample customers indices for all batches at once
    sampled_customers = torch.multinomial(torch.tensor(data_vienna_without_depot['id'], dtype=torch.float),
                                          num_samples=batch_size * customers_count, replacement=True)

    sampled_customers = sampled_customers.reshape(batch_size, customers_count)

    # Gather the sampled locations using the indices
    sampled_locations = data_vienna_without_depot.loc[sampled_customers.flatten()].reset_index(drop=True)

    # Reshape the locations to match the batch size
    locations = sampled_locations.groupby(sampled_locations.index // customers_count)

    # Create PyTorch tensors for the batched data
    locations_tensors = []
    for _, batch in locations:
        id_tensor = torch.tensor(batch['id'].values, dtype=torch.long)
        coords_tensor = torch.tensor(batch[['xcoords', 'ycoords']].values, dtype=torch.float)
        batch_tensor = torch.cat((id_tensor.unsqueeze(1), coords_tensor), dim=1)
        locations_tensors.append(batch_tensor)

    return torch.stack(locations_tensors)

def get_edges_attributes(batch_size, graph, depot, locations, V):

    # all customers ID inclusing depot

    print('Initialzing edges')
    edge_depot = torch.zeros((batch_size, 1, 1))
    edge_depot[:,:,:1] = depot[0][0]
    edge_data = torch.cat((edge_depot, locations[:,:,None,0]), dim=1)

    # generate edge index
    edges_index = []

    for i in range(V+1):
        for j in range(V+1):
            edges_index.append([i, j])
    edges_index = torch.LongTensor(edges_index)
    edges_index = edges_index.transpose(dim0=0,dim1=1)

    # generate nodes attributes
    edges_batch = []

    for batch in edge_data:
        edges = np.zeros((V+1, V+1, 1))
        for i, id1 in enumerate(batch):
            for j, id2 in enumerate(batch):
                distance = precompute_shortest_path(graph, int(id1), int(id2))
                edges[i][j][0] = distance

        edges = edges.reshape(-1, 1)
        edges_batch.append(torch.from_numpy(edges))

    return edges_index, torch.stack(edges_batch)


def generateRandomDynamicRequests(batch_size=2 ,
                                  V=20,
                                  V_static=10,
                                  fDmean=10,
                                  fDstd=2.5,
                                  Lambda=0.025,
                                  horizon=400,
                                  dep = 0,
                                  u = 0):
    gen = random.Random()
    gen.seed() # uses the default system seed
    unifDist = gen.random # uniform distribution
    durDist = lambda: max(0.01, gen.gauss(fDmean, fDstd)) # normal distribution with fDmean and fDstd

    # TODO: in actual data , we need to add a depo node with corrdinate, which should be removed from selected
    #       nodes as well.

    requests = []
    for b in range(batch_size):

        static_request = []
        dynamic_request = []
        u = 0

        while True:
            unif = unifDist()
            u += -(1/Lambda) * math.log(unif)
            if u > horizon or len(dynamic_request) > (V-V_static+2):
                break
            d = round(durDist(),2)
            while d<=0:
                d = round(durDist(),2)

            dynamic_request.append([d, round(u,2)])

        for j in range(V-len(dynamic_request)):
            d = round(durDist(),2)
            while d<=0:
                d = round(durDist(),2)
            static_request.append([d,0])

        request = static_request+dynamic_request
        random.shuffle(request)
        requests.append(request)

    return torch.tensor(requests)

In [61]:
class DVRPSR_Dataset(Dataset):

    customer_feature = 4 # customer features location (x_i,y_i) and duration of service(d), appearance (u)

    @classmethod
    def create_data(cls,
                    batch_size = 2,
                    vehicle_count = 2,
                    vehicle_speed = 20, # km/hr
                    Lambda = 0.025, # request rate per min
                    dod = 0.5,
                    horizon = 400,
                    fDmean = 10,
                    fDstd = 2.5):


        # static customer counts V = Lambda*horizon*(1-dod)/(dod+0.5)
        V_static = int(Lambda*horizon*(1-dod)/(dod)+0.5)

        # total customer count
        V = int(Lambda*horizon/(dod) + 0.5)

        size = (batch_size, V, 1)
        
        # initialize the graph of vienna network
        graph = initialize_graph()

        # get the coordinates of customers
        data_vienna = pd.read_csv('../vienna_data/vienna_cordinates.csv')

        # get depot coordinates: Id, xcoords, ycoords
        depot = get_depot_location(data_vienna)

        # get location of customers: id, xcoords, ycoords
        locations = get_customers_coordinates(data_vienna, batch_size, V, depot)

        # get edges index and attributes, which is distance between one node to others n_i*n_j
        edges_index, edges_attributes = get_edges_attributes(batch_size, graph, depot, locations, V)
        
        ### generate Static_Dynamic customer requests
        dynamic_request = generateRandomDynamicRequests(batch_size,
                                                            V,
                                                            V_static,
                                                            fDmean,
                                                            fDstd,
                                                            Lambda,
                                                            horizon)

        customers = torch.zeros((batch_size,V,cls.customer_feature))
        customers[:,:,:2] = locations[:,:,1:]
        customers[:,:,2:4] = dynamic_request



        depo = torch.zeros((batch_size, 1, cls.customer_feature))
        depo[:,:,0:2] = torch.from_numpy(depot[0][1:])
        depo[:,:,2] =  0

        nodes = torch.cat((depo, customers), 1)
        
        dataset = cls(vehicle_count, vehicle_speed, horizon, nodes, V, 
                      edges_index, edges_attributes, customer_mask = None)
        
        return dataset
    
    def __init__(self, vehicle_count, vehicle_speed, horizon, nodes, V,
                 edges_index, edges_attributes, customer_mask=None):
        
        self.vehicle_count = vehicle_count
        self.vehicle_speed = vehicle_speed
        self.nodes = nodes
        self.vehicle_time_budget = horizon
        self.edges_index = edges_index
        self.edges_attributes = edges_attributes

        self.batch_size, self.nodes_count, d = self.nodes.size()

        if d!= self.customer_feature:
            raise ValueError("Expected {} customer features per nodes, got {}".format(
                self.customer_feature, d))

        self.customer_mask = customer_mask
        self.customer_count = V
    
     
    def __len__(self):
        return self.batch_size


    def __getitem__(self, i):
        if self.customer_mask is None:
            return self.nodes[i]
        else:
            return self.nodes[i], self.customer_mask[i]

    def nodes_generate(self):
        if self.customer_mask is None:
            yield from self.nodes
        else:
            yield from (n[m^1] for n,m in zip(self.nodes, self.customer_mask))  
            
            
    def normalize(self):
        loc_max, loc_min = self.nodes[:,:,:2].max().item(), self.nodes[:,:,:2].min().item()
        loc_max -= loc_min
        edge_max_length = self.edges_attributes[:,:,0].max().item()

        self.nodes[:,:,:2] -= loc_min
        self.nodes[:,:,:2] /= loc_max
        self.nodes[:,:,2:] /=self.vehicle_time_budget

        self.vehicle_speed *= self.vehicle_time_budget/edge_max_length
        self.vehicle_time_budget = 1
        return loc_max, 1

    def save(self, folder_path):
        torch.save({
            'veh_count':self.vehicle_count,
            'veh_speed':self.vehicle_speed,
            'nodes':self.nodes,
            'edges_index':self.edges_index,
            'edges_attributes':self.edges_attributes,
            'customer_count':self.customer_count,
            'cust_mask':self.cust_mask
        }, folder_path)

    @classmethod
    def load(cls, folder_path):
        return cls(**torch.load(folder_path))
        
        
        
        

In [62]:
data = DVRPSR_Dataset.create_data(batch_size=1, vehicle_count=2, Lambda=0.0125, dod=0.5, horizon=400)

Initialzing edges


In [63]:
data.nodes

tensor([[[ 1.5348e+02, -2.7868e+00,  0.0000e+00,  0.0000e+00],
         [ 1.3548e+02,  6.3629e+00,  1.3980e+01,  3.3848e+02],
         [ 1.3853e+02,  4.1748e+01,  1.3850e+01,  1.3171e+02],
         [ 1.5720e+02,  3.8793e+01,  7.7900e+00,  1.5093e+02],
         [ 1.2608e+02,  1.9041e+00,  9.2000e+00,  3.4049e+02],
         [ 1.3274e+02,  7.2597e+00,  1.1460e+01,  0.0000e+00],
         [ 1.1312e+02, -7.5473e-02,  1.0030e+01,  0.0000e+00],
         [ 1.2074e+02,  1.7892e+01,  1.2050e+01,  6.1810e+01],
         [ 1.4845e+02, -8.4152e+00,  1.1620e+01,  3.1111e+02],
         [ 1.3364e+02, -4.9474e+00,  8.5200e+00,  1.9118e+02],
         [ 1.3663e+02,  2.6947e+00,  9.9400e+00,  1.1331e+02]]])

In [64]:
data.edges_attributes

tensor([[[    0.0000],
         [ 8528.7071],
         [21696.1956],
         [19061.6620],
         [11161.3693],
         [ 9821.1578],
         [18955.1887],
         [24534.7807],
         [ 3749.3110],
         [10543.2372],
         [ 7620.2595],
         [ 8808.3717],
         [    0.0000],
         [20078.6634],
         [17444.1297],
         [ 3233.8395],
         [ 1292.4506],
         [ 6954.6278],
         [ 6873.3717],
         [ 9245.7757],
         [ 4124.6964],
         [ 1034.3410],
         [16867.5184],
         [12569.9681],
         [    0.0000],
         [ 7453.6376],
         [20377.9866],
         [13862.4188],
         [28171.8061],
         [13206.4928],
         [17304.9224],
         [19759.8545],
         [16836.8768],
         [16346.6555],
         [17224.4616],
         [11525.0083],
         [    0.0000],
         [19857.1238],
         [18516.9122],
         [27650.9432],
         [14138.3445],
         [16784.0596],
         [19238.9917],
         [1

In [65]:
edges = torch.pairwise_distance(data.nodes[:,0,:2], data.nodes[:,1,:2])
edges

tensor([20.1910])

In [70]:
edges_real = data.edges_attributes[0,1][0]
edges_real

tensor(8528.7071, dtype=torch.float64)

In [71]:
edges_real/25000

tensor(0.3411, dtype=torch.float64)

In [75]:
(edges_real/(20*1000/60))/600

tensor(0.0426, dtype=torch.float64)

In [74]:
edges/

tensor([20.1910])

In [13]:
coordinates = pd.read_csv("./vienna_data/vienna_dist.csv", header = None, sep=' ')
coordinates.head()

0      1           2
0  0   1367  112.736160
1  0  10445  176.062978
2  1  12881   92.183050
3  1   2676   16.391515
4  2   2664  173.987554

In [58]:
data.edges_attributes.view((2, 161, 161)).size()

torch.Size([2, 161, 161])

In [59]:
data.edges_attributes.size()

torch.Size([2, 25921, 1])

In [53]:
data.nodes.size()

torch.Size([2, 108, 4])

In [33]:
graph = DVRPSR_Dataset.initialize_graph()

In [60]:
dist = nx.shortest_path_length(graph, 2, 0, weight='weight')
dist

544.0006549938314

In [35]:
# TODO: distance need to be normalized afterwords
shortest_path_length = sum(graph.get_edge_data(u, v)['weight'] 
                                   for u, v in zip(shortest_path, shortest_path[1:]))
shortest_path_length

565.2582942952082

In [61]:
path = nx.shortest_path(graph, 2, 0)
path

[2, 2664.0, 14941.0, 10443.0, 10445.0, 0]

In [22]:
shortest_path = nx.shortest_path(graph, 0, 2)
shortest_path

[0, 10445.0, 2671.0, 2669.0, 10401.0, 2676.0, 2]

In [181]:
 # reset vehicle (minibatch*veh_count*veh_feature)
    
minibatch = 3
vehicle_count = 2
vehicle_feature = 8
customer_feature = 4
vehicle_budget = 400
init_cust_mask = None
nodes_count = 21
customer_size = 21

In [182]:
distance_mat = data.edges_attributes.view((minibatch, customer_size, customer_size))

In [183]:


nodes = data.nodes

vehicles = nodes.new_zeros((minibatch, vehicle_count, vehicle_feature))
vehicles[:, :, :2] = data.nodes[:, :1, :2]
vehicles[:, :, 2] = data.vehicle_time_budget


# reset vehicle done
veh_done = nodes.new_zeros((minibatch, vehicle_count), dtype=torch.bool)
done = False

# reset cust_mask
customer_mask = nodes[:, :, 3] > 0
if init_cust_mask is not None:
    customer_mask = customer_mask | init_cust_mask

# reset new customers and served customer since now to zero (all false)
new_customer = True
served = torch.zeros_like(customer_mask)

# reset mask (minibatch*veh_count*nodes)
mask = customer_mask[:, None, :].repeat(1, vehicle_count, 1)

# reset current vehicle idx, current vehicle, current vehicle mask
current_vehicle_index = nodes.new_zeros((minibatch, 1), dtype=torch.int64)
current_vehicle = vehicles.gather(1, current_vehicle_index[:, :, None].expand(-1, -1, vehicle_feature))
current_vehicle_mask = mask.gather(1, current_vehicle_index[:, :, None].expand(-1, -1, nodes_count))

In [202]:
customer_index = torch.tensor([[4],[5],[2]])
dest = nodes.gather(1, customer_index[:, :, None].expand(-1, -1, customer_feature))
current_vehicle[:,:,4] = customer_index

dist = torch.zeros((minibatch, 1))
for i in range(minibatch):
    dist[i,0] = distance_mat[i][int(current_vehicle[i,:,4])][int(current_vehicle[i,:,5])]
    


In [203]:
dist

tensor([[0.],
        [0.],
        [0.]])

In [204]:
dist_pair = torch.pairwise_distance(current_vehicle[:, 0, :2], dest[:, 0, :2], keepdim=True)
dist_pair


tensor([[27.7970],
        [34.0259],
        [34.1713]])

In [205]:
current_vehicle

tensor([[[153.4832,  -2.7868, 400.0000,   0.0000,   4.0000,   4.0000,   0.0000,
            0.0000]],

        [[153.4832,  -2.7868, 400.0000,   0.0000,   5.0000,   5.0000,   0.0000,
            0.0000]],

        [[153.4832,  -2.7868, 400.0000,   0.0000,   2.0000,   2.0000,   0.0000,
            0.0000]]])

In [206]:
cost = torch.zeros((minibatch, customer_size,1))
for i in range(minibatch):
    for j in range(customer_size):
        dist_vehicle_customer_depot = distance_mat[i][int(current_vehicle[i, :, 4])][j] + \
                                      distance_mat[i][j][0]
        cost[i,j] = dist_vehicle_customer_depot

In [207]:
cost

tensor([[[12073.8242],
         [12147.1133],
         [31129.9609],
         [37056.2383],
         [12073.8242],
         [12410.2979],
         [23182.2988],
         [26576.6523],
         [16136.9805],
         [14555.1846],
         [11615.3086],
         [12442.7627],
         [42607.6875],
         [13425.7148],
         [28457.6504],
         [26837.7070],
         [41775.5234],
         [24483.6934],
         [25110.4375],
         [23246.2363],
         [40783.8203]],

        [[19942.3477],
         [15831.9141],
         [35233.6016],
         [23313.8301],
         [50010.0781],
         [19942.3477],
         [22123.5977],
         [21357.6172],
         [24604.2949],
         [22227.8223],
         [30858.2832],
         [26969.6445],
         [48152.0039],
         [22627.5508],
         [22856.3594],
         [36536.7461],
         [24623.3574],
         [14645.5352],
         [24672.2383],
         [50429.2031],
         [47135.8164]],

        [[14458.9795],
       

In [233]:
import torch

# Assuming distance_mat is a tensor of shape (batch_size, customer_size, customer_size)
# And current_vehicle is a tensor of shape (batch_size, num_vehicles, vehicle_feature)

# Get the indices of the current vehicle and destination nodes
source_indices = current_vehicle[:, :, 4].long()
destination_indices = current_vehicle[:, :, 5].long()

# Gather the distances for each vehicle
dist = distance_mat.gather(1, source_indices)  # Gather distances from source indices
dist = dist.gather(2, destination_indices)  # Gather distances to destination indices

# Note: Make sure `distance_mat` and `current_vehicle` are torch.Tensors and have the correct shapes and data types.


RuntimeError: Index tensor must have the same number of dimensions as input tensor

In [234]:
distance_mat.size()

torch.Size([3, 21, 21])

In [235]:
source_indices = source_indices.unsqueeze(-1).long()

In [219]:
destination_indices

tensor([[4],
        [5],
        [2]])

In [236]:
dist_source = distance_mat.gather(1, source_indices)  
dist_source

tensor([[[12073.8241]],

        [[19942.3471]],

        [[14458.9796]]], dtype=torch.float64)

In [214]:
dist_dest = dist = distance_mat.gather(2, destination_indices)  
dist_dest

tensor([[[11161.3693]],

        [[20370.8089]],

        [[21599.6604]]], dtype=torch.float64)

In [143]:
current_vehicle

tensor([[[153.4832,  -2.7868, 400.0000,   0.0000,   2.0000,   2.0000,   0.0000,
            0.0000]],

        [[153.4832,  -2.7868, 400.0000,   0.0000,   3.0000,   3.0000,   0.0000,
            0.0000]]])